#!/bin/bash
SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )
TMP_FILE="${SCRIPT_DIR}/query.xhtml";

if [ $# -lt 1 ]; then 
  read -p "Search anime: " query;
else
  query=$(echo "$@" | awk '{$1=$1};1');
fi

query=$(echo "$query" | tr ' ' '+');
curl -s "https://nyaa.si/?page=rss&f=0&c=1_2&q=${query}" > "$TMP_FILE";
xml_data=$(xmllint --xpath '//item/title/text() | //item/link/text()' "$TMP_FILE");
rm -rf "$TMP_FILE";

titles=();
links=();
sequence=0;

while IFS= read -r line; do
  if [ $sequence == 0 ]; then
    titles+=("$line");
  elif [ $sequence == 1 ]; then
    links+=("$line");
  fi
  ((sequence+=1));
  if [ $sequence == 2 ]; then
    sequence=0;
  fi
done <<< "$xml_data"

for index in "${!titles[@]}"; do
    element="${titles[index]}";
    printf "%2d) %s\n" "$index" "$element"
done

while true
do
  echo;
  read -p "Choose an option: " option;
  echo;
  if [ "$option" == "q" ] || [ "$option" == "quit" ]; then
    exit;
  elif ! [[ "$option" =~ ^[0-9]+([,-][0-9]*)?$ ]]; then
    echo "Invalid option";
    exit 1;
  else
    start="$(echo $option | tr '-' ',' | cut -d',' -f1,1)";
    end="$(echo $option | tr '-' ',' | cut -d',' -f2,2)";
    if [ "$start" -gt "$end" ] || [ "$end" -gt "$index" ]; then
      echo "Invalid option";
      exit 1;
    fi
    for ((i=$start; i<=$end; i++))
    do
      transmission-remote -a "${links[$i]}" 1>/dev/null &&
      echo -e "Transmission: ${titles[$i]}";
    done
  fi
done
